language: go
go:
  - 1.3
  - 1.4

before_install:
 - gem install fluentd --no-ri --no-rdoc
 - fluentd -c fluentd.conf &

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -v github.com/revel/revel
  - go get -v github.com/revel/cmd/revel

script:
  - go test github.com/revel/revel

  # Build & run the sample app
  - revel test github.com/janekolszak/revfluent/testapp
