language: go
go: 1.2
services:
  - fluentd
install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -v github.com/revel/revel
  - go get -v github.com/revel/cmd/revel

script:
  - go test github.com/revel/revel

  # Build & run the sample app
  - revel test github.com/janekolszak/revfluent/testapp
